### PR TITLE
Update to 11.0

### PR DESCRIPTION
**Pull request by puxplaying**
Hi, that was my first try to build a flatpak, seems it worked out!

### CODE REVIEW

**Comment by Garbulix** [comment]
I bless this PR.
Can you merge this instead of mine?
I made a lot of mess because of hurry and now I am afraid to mess more (also because of hurry).

**Comment by kparal** [comment]
@puxplaying I wanted to fix the whitespace that was off, but this PR says "puxplaying wants to merge 1 commit into flathub:master from **unknown repository**". I assume that means you already deleted the branch or the whole forked repo? So I'll have to make the change just locally. I'm commenting on this just to let you know.

**Comment by kparal** [comment]
Ah, it was a <tab> instead of <space> being used.

**Comment by kparal** [comment]
Merged in the referenced commit.

**Pull request closed without merging**
