### PR TITLE
merge beta to master

### PR DESCRIPTION
**Pull request by kparal**
@Garbulix Have time to test?

### CODE REVIEW

**Comment by Garbulix** [comment]
On Friday I think

**Comment by Garbulix** [comment]
I tried to install it but I receive 404 error. I have low experience with these tools so I halted my testing.

**Comment by kparal** [comment]
You're right, for some reason that build doesn't exist anymore. I could trigger a new one, but perhaps an easier solution is to switch to the beta branch of FreeFileSync? That way you always have the latest version (there is usually a 1-day delay between pushing to the beta branch + creating a PR like this one, and having the build available to beta branch users). You just run `flatpak update` and that's it.

If you want to switch to the beta branch:
https://github.com/flathub/org.freefilesync.FreeFileSync?tab=readme-ov-file#get-involved

**Comment by Garbulix** [comment]
I switched to beta branch and tested - it looks fine.

**Comment by kparal** [comment]
Thanks, merging.

**Pull request merged**
