### PR TITLE
upstream release 11.15

### PR DESCRIPTION
**Pull request by kparal**
@Garbulix Do you have time to test this?

### CODE REVIEW

**Comment by hfiguiere** [comment]
for the record this created a "beta" branch, which mean there is a version on flathub beta.  In case that wasn't intended.

**Comment by kparal** [comment]
> for the record this created a "beta" branch, which mean there is a version on flathub beta. In case that wasn't intended.

It is intended, the `beta` branch existed even before, I use it before pushing the build stable :-)

**Comment by kparal** [comment]
It seems to be working well for me, so I'm merging this.

**Comment by Garbulix** [comment]
Maybe I will be able to help you next time 😅

**Pull request merged**
